//the main differences between an Album and a Playlist is that, while Albums are artist-generated and have customizable covers, playlists are listener-generated and their covers are autogenerated based on the first 4 songs
import 'package:flutter/material.dart';
import 'package:innertune_replica/entities/song.dart';
import 'package:innertune_replica/widgets/playlistScreen.dart';

class Album {
  String name;
  String artist;
  List<Song> songs;
  String coverImageUrl;

  Album(this.name,this.artist,this.songs,this.coverImageUrl);
}